## YAML Template.
---
version: 0.2

run-as: root

phases:
  install:
    run-as: root
    on-failure: ABORT
    runtime-versions:
      nodejs: 16
    commands:
      - node --version
      - npm --version
      - npm install -g @angular/cli@14
      - npm install
  build:
    run-as: root
    on-failure: ABORT
    commands:
      - npm run build
    finally:
      - cp src/configs/config.dev.json dist/configs/config.json
      - cp appspec.yml dist
artifacts:
  files:
        - '**/*'
  base-directory:
        'dist'
