apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
  namespace: dev
  labels:
    app: frontend-app
spec:
  selector:
    matchLabels:
      app: frontend-app
  replicas: 2
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
      - name: frontend
        image: 331879450537.dkr.ecr.us-west-2.amazonaws.com/frontend:latest
        ports:
            - containerPort: 80
